name: CI pipeline

on:
  pull_request:
    paths:
      - '**.py'
      
jobs:
  lint:
    name: checkout
    runs-on: ubuntu-24.04
    # if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: install dependencies
        run: pip install -r requirements-dev.txt

      - name: Running isort.
        run: isort --check-only  .

      - name: Running flake8
        run: flake8 .
